# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e881351d6e876623776109f8e2596de1c2fbdbeb17fca982cca9b7ed5c0c7e53ae45262a5a69a0f4b301ca67e9e455027d650a2a3fa2b5dea0e5e6db887b114e

test:
  secret_key_base: d2d4d983af7e7d4c870465c364fddfad0eed1925efab03b4d9cb0e80e586ee747c07d8f7cf1d60017e8289ee0a13b483b2a039d46af7f6291f2cf1257e181ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
